# Development override for docker-compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    command: uvicorn wati.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
  
  frontend:
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    command: npm run serve -- --port 8080 --host 0.0.0.0
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:8000